# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: beeauvin/swiftly-swift@v1
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-swift-testing -v
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      uses: raphaelbussa/swiftlint-action@main
      with:
        subcommand: lint --strict

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: compnerd/gha-setup-swift@main
      with:
        swift-version: swift-6.1.2-release
        swift-build: 6.1.2-RELEASE
    - name: Cache
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-swift-testing -v
  
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-swift-testing -v
  
